name: Fix Lockfile

on:
  workflow_dispatch:

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install

      - name: Commit updated lockfile
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add package-lock.json
          git commit -m "chore: update lockfile for overrides" || echo "No changes"
          git push
